[versions]
#noinspection AndroidGradlePluginVersion (Upgrade it after migrate to compose aboutLibraries required to Gradle 9) for more: https://github.com/mikepenz/AboutLibraries/issues/1090#issuecomment-2761198419
agp = "8.13.2"
kotlin = "2.3.10"
preference = "1.2.1"
appcompat = "1.7.1"
fragment = "1.8.9"
navigation = "2.9.7"
lifecycle = "2.10.0"
material = "1.14.0-alpha09"
aboutLibraries = "13.2.1"

[libraries]
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-fragment = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
androidx-lifecycle-viewmodel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
aboutlibraries-view = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutLibraries" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutLibraries" }